// Code generated by "next 0.0.4"; DO NOT EDIT.

package ginserver

import "github.com/gin-gonic/gin"
import "github.com/gopherd/components/httpserver"
import "github.com/gopherd/core/op"

var _ = (*gin.Engine)(nil)
var _ = (*httpserver.Component)(nil)
var _ = op.SetOr[any]

// Name represents the ginserver component name.
const Name = "github.com/gopherd/components/ginserver";

type Options struct {
	// Addr is the address to listen on.
	Addr string
	// Block indicates whether the Start method should block.
	Block bool
}

func (x *Options) OnLoaded() {
}

type Component interface {
	httpserver.Component

	Engine() *gin.Engine
}
