// Code generated by "next 0.0.4"; DO NOT EDIT.

package blocker

import "github.com/gopherd/core/op"

var _ = op.SetDefault[any]

// Name represents the blocker component name.
const Name = "github.com/gopherd/components/blocker";

type Options struct {}

func (x *Options) OnLoaded() {
}
