// Code generated by "next 0.0.4"; DO NOT EDIT.

package asyncq

import "github.com/gopherd/core/op"

var _ = op.SetOr[any]

// Name represents the asyncq component name.
const Name = "github.com/gopherd/components/asyncq";

// Options represents the component options.
type Options struct {
	// LockThread determines if the consumer goroutine should be bound to an OS thread.
	LockThread bool
	// MaxSize is the maximum number of requests allowed in the queue.
	// Requests exceeding this limit will be discarded.
	MaxSize int
	// NumConsumers is the number of consumer goroutines to run concurrently.
	NumConsumers int
}

func (x *Options) OnLoaded() {
	op.SetOr(&x.MaxSize, 1048576)
}
