// Code generated by "next 0.0.4"; DO NOT EDIT.

package echoserver

import echo "github.com/labstack/echo/v4"
import "github.com/gopherd/components/httpserver"
import "github.com/gopherd/core/op"

var _ = (*echo.Echo)(nil)
var _ = (*httpserver.Component)(nil)
var _ = op.SetDefault[any]

// Name represents the echoserver component name.
const Name = "github.com/gopherd/components/echoserver";

type Options struct {
	// Addr is the address to listen on.
	Addr string
	// Block indicates whether the Start method should block.
	Block bool
}

func (x *Options) OnLoaded() {
}

type Component interface {
	httpserver.Component

	Engine() *echo.Echo
}
