// Code generated by "next 0.2.8"; DO NOT EDIT.

package syncq

import "github.com/gopherd/core/op"

var _ = op.SetDefault[any]

// Name represents the syncq component name.
const Name = "github.com/gopherd/components/syncq";

// Options defines the configuration options for the syncq component.
type Options struct {
	// Unordered determines if listeners should be invoked in the order they are added.
	Unordered bool
	// Concurrent determines if listeners should be invoked concurrently.
	Concurrent bool
}

func (x *Options) OnLoaded() {
}
