// Code generated by "next 0.0.4"; DO NOT EDIT.

package db

import "gorm.io/gorm"
import "github.com/gopherd/core/op"

var _ = (*gorm.DB)(nil)
var _ = op.SetDefault[any]

// Name represents the db component name.
const Name = "github.com/gopherd/components/db";

// Options represents the database component options.
type Options struct {
	// The database driver name.
	Driver string
	// The data source name.
	DSN string
}

func (x *Options) OnLoaded() {
}

// Component represents the database component API.
type Component interface {
	Engine() *gorm.DB
}
