// Code generated by "eventer"; DO NOT EDIT.

package loggerapi

import (
	"reflect"
	"context"

	"github.com/gopherd/core/event"
)

// Generated for SetLevelEvent
var SetLevelEventType = reflect.TypeOf((*SetLevelEvent)(nil))

func (*SetLevelEvent) Typeof() reflect.Type {
	return SetLevelEventType
}

func SetLevelEventListener(h func(context.Context, *SetLevelEvent) error) event.Listener[reflect.Type] {
	return event.Listen(SetLevelEventType, h)
}
