// Code generated by "next 0.0.4"; DO NOT EDIT.

package tcpserver

import "github.com/gopherd/core/op"

var _ = op.SetOr[any]

// Name represents the tcpserver component name.
const Name = "github.com/gopherd/components/tcpserver";

// Options represents the configuration options for the TCP server.
type Options struct {
	// Network represents the network type, either tcp or unix.
	Network string
	// Addr represents the host:port address.
	Addr string
	// KeepAlive specifies the keep-alive period for an active network connection.
	KeepAlive int
	// ReadTimeout specifies the maximum duration for reading the entire request.
	ReadTimeout int
	// WriteTimeout specifies the maximum duration before timing out writes of the response.
	WriteTimeout int
}

func (x *Options) OnLoaded() {
}
