// Code generated by "next 0.2.6"; DO NOT EDIT.

package httpserver

import "net/http"
import "github.com/gopherd/core/op"

var _ = (*http.Handler)(nil)
var _ = op.SetDefault[any]

// Name represents the httpserver component name.
const Name = "github.com/gopherd/components/httpserver";

type Options struct {
	// Addr is the address to listen on.
	Addr string
	// Block indicates whether the Start method should block.
	Block bool
	// NewMux indicates whether to create a new ServeMux.
	NewMux bool
}

func (x *Options) OnLoaded() {
}

type Component interface {
	// Handle registers the handler for the given pattern and methods.
	// If method is empty, it registers the handler for all methods.
	Handle(methods []string, path string, handler http.Handler)
	// HandleFunc registers the handler function for the given pattern and methods.
	// If method is empty, it registers the handler for all methods.
	HandleFunc(methods []string, path string, handler http.HandlerFunc)
}
